#!/bin/bash
#start
#
#The goal of this script is to calculate the amount of cookies cooks need to cook a cookie cake given certain parameters.

#The variable names in this are horrible but I'm too lazy to fix it right now.

#Data about the tray
echo -n "Please enter the lenght and width of the cooking tray (in cm): "
read -r tlenght twidth

#Data about the cookies
echo -n "Please enter the lenght and width of the cookies (in cm): "
read -r clenght cwidth
echo -n "How many cookies are there in one pack?"
read -r amount

#How many layers?
echo -n "How many layers do you want for the cake?"
read -r layersAmount


#Calculations
let "trayArea = $tlenght * $twidth"
let "cookieArea = $clenght * $cwidth" 
let "layerArea = $trayArea / $cookieArea"
let "cookiesNeeded = $layerArea * $layersAmount"
let "packetAmount = $cookiesNeeded / $amount"
let "extraCookies = $cookiesNeeded % $amount" 

#Answer
echo "You need $packetAmount packs of cookies and $extraCookies cookies on top of that!"


